In [ ]:
%%javascript
function clear_other_cells () {
document.getElementById('file_menu').parentNode.style.display = 'none';
document.getElementById('logout').style.display = 'none';
document.getElementById('notebook_name').style.display = 'none';
var this_cell = $(element).closest('.cell').data('cell');
Jupyter.notebook.get_cells().forEach(function (cell) {
if (cell.cell_type === 'code' && cell !== this_cell) {
cell.clear_output();
}
Jupyter.notebook.set_dirty(true);
});
};
$([IPython.events]).on('notebook_loaded.Notebook', clear_other_cells());
$(window).on("beforeunload", function(){
Jupyter.notebook.kernel.restart();
});
$([IPython.events]).on('notebook_loaded.Notebook', function() {
Jupyter.notebook.set_autosave_interval(0);
});

<ul style="list-style-type:circle;font-size:14px;line-height:27px;">
    <li><b>from streamanalytix.python.dataset import Dataset:</b> Load Dataset class from streamanalytix API.</li>
	<li><b>Dataset(source_name):</b> Creates object of dataset class for given source.
		<ul>
			<li><b>Dataset.get_dataframe():</b> Read data source and return a pandas dataframe. </li>
		</ul>
	</li>
	<li><b>from streamanalytix.utilities import sax_utils:</b> Load sax_util script. It has following functions
		<ul>
			<li><b>sax_utils.save_and_download_model(model_name, model_object):</b>This method lets the user to save and download the trained model with StreamAnalytix. This model can than be used for training and/or scoring purpose as part of the StreamAnalytix pipeline</li>
				<ul>
					<li><b>model_name:</b> Name of the model. Accepted String value only. e.g. <i>"DecisionTreeModel"</i></li>
					<li><b>model_object:</b> Object of the trained model</li>
				</ul>
			<li><b>sax_utils.get_h2o_cluster_url(cluster_name):</b>This method lets the user to get h2o cluster url by providing cluster name</li>
				<ul>
					<li><b>cluster_name:</b> Name of the cluster. Accepted String value only. e.g. <i>"TrainingCluster"</i></li>
				</ul>
			<li><b>sax_utils.upload_and_register_h2o_model(model_object, model_name, model_type, project_name, project_version):</b>This method lets the user to upload and register h2o model in 'mojo' format in streamanalytix</li>
				<ul>
					<li><b>model_object:</b> Object of trained H2O model</li>
					<li><b>model_name:</b>Name of the model. Accepted String value only. e.g. <i>"H2OTreeModel"</i>
					<li><b>model_type:</b>Type of trained model. Accepted String value only. We support H2O model of types :<i>"DistributedRandomForest"</i>,<i>"GeneralizedLinearModelling"</i>,<i>"IsolationForest"</i>,<i>"GradientBoostingMachine"</i></li>
					<li><b>project_name:</b>Project Name in which model should register. Accepted String value only. e.g. <i>"MyProject"</i></li>
					<li><b>project_version:</b>Version of given project in which model should register</li>
				</ul>
		</ul>
	</li>
</ul>

In [2]:
from streamanalytix.python.dataset import Dataset
from streamanalytix.utilities import sax_utils


dataset_1 = Dataset("HealthDataset")

# you can use pandas to create dataframe as shown below
# df = dataset_1.get_dataframe()

In [4]:
df = dataset_1.get_dataframe()

In [6]:
df.head()

,contact_id,first_name,last_name,dob,email,phone,address,height,weight,married,race,nationality,disease,incomesource,education
0,867e6a29-4382-4200-9937-a4e6e093691e,Jackie,Woolward,1965-04-22,jwoolward1@livejournal.com,391-665-2141,60374 Beilfuss Street,5.5,105.5,False,Indians,American,Heart,Private Job,High School
1,41027717-c183-4156-a5ac-e1659d3e58e0,Flossy,D'eath,1967-05-23,fdeath3@netscape.com,925-532-6029,66783 Prairie Rose Park,5.1,56.8,True,Anglo-Celtic,Canadian,Asthama,Family Business,High Secondary
2,2c24ad29-4cd3-419c-83c8-2ae0ce4b2281,Romy,Hawkridge,1966-08-14,rhawkridge4@eventbrite.com,183-386-7806,120 Badeau Trail,5.3,128.8,True,Aryan,Chinese,Cancer,Govt. Job,PG
3,2f25c8cc-17a2-4fbb-94d5-036ec13c7064,Eli,Fields,2000-11-25,efields8@blinklist.com,997-452-2775,074 Oxford Street,4.5,97.1,True,Arabs,Mexican,Heart,Private Job,Graduation
4,83a8dc98-895d-461b-93cc-1b63453c3bf8,Filip,Brimfield,2002-06-11,fbrimfield9@w3.org,379-475-4211,669 Linden Avenue,5.6,120.6,True,Arabs,Chinese,Asthama,Private Job,High Secondary